from launch import LaunchDescription
from launch_ros.actions import Node

def generate_launch_description():
    return LaunchDescription([
        Node(
            package='emlid_interface',
            node_namespace='foxtrot',
            node_executable='emlid_interface_node',
            node_name='emlid_interface_node',
            parameters=[
            ]
        ),
        Node(
            package='unitree_ros_bridge',
            node_namespace='foxtrot',
            node_executable='unitree_ros_bridge_server_node',
            node_name='unitree_ros_bridge_server_node',
            parameters=[
            ]
        ),
        Node(
            package='b1_udp_velocity_interface',
            node_namespace='foxtrot',
            node_executable='udp_velocity_interface_node',
            node_name='udp_velocity_interface_node',
            parameters=[
            ]
        ),
        Node(
            package='b1_legged_real',
            node_namespace='foxtrot',
            node_executable='ros2_udp',
            node_name='ros2_udp',
            parameters=[
            ]
        ),
        Node(
            package='heading_controller',
            node_namespace='foxtrot',
            node_executable='heading_controller_node',
            node_name='heading_controller_node',
            parameters=[
                {'kp':5.0},
                {'kd':0.5},
                {'ki':0.01},
            ]
        ),
        Node(
            package='wpt_control_xy',
            node_namespace='foxtrot',
            node_executable='wpt_control_xy_node',
            node_name='wpt_control_xy_node',
            parameters=[
            ]
        ),
        Node(
            package='position_broadcaster',
            node_namespace='foxtrot',
            node_executable='position_broadcaster_node',
            node_name='position_broadcaster_node',
            parameters=[
            ]
        ),
    ])
